// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5UYDL6PocSJufEb5nkFPrX79SV9VCFsc',
    appId: '1:1057597522560:web:d96e1f4b462b3c9fd59c65',
    messagingSenderId: '1057597522560',
    projectId: 'inventory-f144f',
    authDomain: 'inventory-f144f.firebaseapp.com',
    storageBucket: 'inventory-f144f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHactCCZw8Vdi5P8eo-u7QbU95R9e0XOw',
    appId: '1:1057597522560:android:df1498467e9786bdd59c65',
    messagingSenderId: '1057597522560',
    projectId: 'inventory-f144f',
    storageBucket: 'inventory-f144f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCV_9VnbFnU4os1YszL8mtiqwNR7L2o5Qg',
    appId: '1:1057597522560:ios:0cef01cf55a656ebd59c65',
    messagingSenderId: '1057597522560',
    projectId: 'inventory-f144f',
    storageBucket: 'inventory-f144f.appspot.com',
    iosClientId: '1057597522560-idcmscgb1bf05ae3fi9ev4ujc2sod7vt.apps.googleusercontent.com',
    iosBundleId: 'com.example.stockManagement',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCV_9VnbFnU4os1YszL8mtiqwNR7L2o5Qg',
    appId: '1:1057597522560:ios:0cef01cf55a656ebd59c65',
    messagingSenderId: '1057597522560',
    projectId: 'inventory-f144f',
    storageBucket: 'inventory-f144f.appspot.com',
    iosClientId: '1057597522560-idcmscgb1bf05ae3fi9ev4ujc2sod7vt.apps.googleusercontent.com',
    iosBundleId: 'com.example.stockManagement',
  );
}
